name = "Arch"
license = "MIT"
licenselink = "https://github.com/syui/hugo-theme-air/blob/master/LICENSE.md"
description = "Arch Linux Themes"
homepage = "https://syui.github.io/hugo-theme-arch"
tags = ["blog"]
features = ["arch linux","bootstrap", "talaria"]
min_version=0.15

[author]
  name = "syui"
  homepage = "https://syui.github.io"

[original]
    author = "archlinux"
    homepage = "https://archlinux.org"
    repo = "https://github.com/archlinux/archweb"
