name = "Potato Dark"
license = "MIT"
licenselink = "https://github.com/surajmandalcell/potato-dark/blob/master/LICENSE.md"
description = "Potato Dark is a modern, simple and beautiful Hugo theme"
source_repo = "git@github.com:surajmandalcell/potato-dark.git"
tags = ["Responsive", "Blog", "Google analytics", "Disqus", "Clean", "Tags", "Minimal", "Minimalist", "Simple", "White", "Starter"]
features = ["blog"]
min_version = 0.27
[author]
    name = "SurajMandal"
    homepage = "https://surajmandalcell.github.com/"
