name = "Hugotube"
license = "MIT"
licenselink = "https://github.com/marcanuy/hugotube/blob/master/LICENSE.md"
description = "A responsive Hugo theme based on Youtube layout."
homepage = "https://github.com/marcanuy/hugotube"
tags = ["bootstrap", "youtube", "bootstrap4"]
features = ["responsive", "bootstrap4", "youtube"]
min_version = 0.31

[author]
  name = "Marcelo Canina"
  homepage = "https://marcanuy.com"
