name = "Remark Twemoji"
license = "MIT"
licenselink = "https://github.com/eueung/hugo-remark-twemoji/blob/master/LICENSE.md"
description = "Remark Twemoji - Conversational (Tw)emoji remark.js slides with Hugo"
homepage = "https://github.com/eueung/hugo-remark-twemoji/"
tags = ["presentation", "slide", "remark", "google analytics", "custom themes"]
features = ["remark.js", "pre-made templates", "shortcodes"]
min_version = 0.18

[author]
    name = "Eueung Mulyana"
    homepage = "https://eueung.github.io/"

