name = "Shapez Theme"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
homepage = ""
tags = ["hugo", "blog", "Shapez", "SVG", "design"]
min_version = 0.16

[author]
  name = "djuelg"
  homepage = "https://github.com/djuelg"