baseurl = ""
languageCode = "en-gb"
title = "HPSTR"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "hpstrhugo"

[params]
	subtitle = "An elegant, responsive theme for Hugo"
	[params.author]
		name = "HPSTR"
		avatar = "/images/avatar.jpg"
		bio = "An elegant, responsive theme for Hugo"
		github = "dldx/hpstr-hugo-theme"
	[params.image]
	  feature = "/images/abstract-1.jpg"
	  credit = "dargadgetz"
	  creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
