baseurl = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hugo Theme Dream"
theme = "hugo-theme-dream"

copyright = "Copyright (c) 2018, g1eny0ung; all rights reserved."

# enableRobotsTXT = true

# googleAnalytics = ""

# disqusShortname = ""

[params]
  author = "Author"
  motto = "Motto"
  # description = ""
  # avatar = ""
  
  # email = ""
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""
