baseurl = "http://mysite.com/"
languageCode = "en-us"
title = "My Awesome Site"
theme = "rocktopus"
GoogleAnalytics = "abcde"
paginate = 4
MetaDataFormat = "toml"
[permalinks]
    post = "/:year/:month/:title/"
[taxonomies]
    tags = "tags"
    series = "series"
[author]
    name = "someperson"
[params]
	# supports either dark or light color scheme
	colorscheme = "light"
    # text for the header section
    blogHeader = "<span style=\"font-size: 36px; \">my<b>Site</b></span>"
    tagline = "something witty"
    # the theme assumes this will be in your static/img directory
    headerimg = "City-Under-Heat.jpg"
    # used for the contact page (if you use it)
    contactEmail = "me@mysite.com"
    contactTwitter = "me"
[menu]
    # Menu for the nav bar.
    # Ideal count is 3 items, see demo site for an example
    [[menu.nav]]
    identifier = "projects"
    name       = "projects"
    url        = "/series"
    weight     = 0

    [[menu.nav]]
    identifier = "code"
    name       = "code"
    url        = "https://github.com/esell/"
    weight     = 1

    [[menu.nav]]
    identifier = "contact"
    name       = "contact"
    url        = "/contact"
    weight     = 2
