name = "revealjs"
license = "MIT"
licenselink = "https://github.com/RealOrangeOne/hugo-theme-revealjs/blob/master/LICENSE"
homepage = "https://github.com/RealOrangeOne/hugo-theme-revealjs"
tags = ["presentation", "revealjs"]
features = ["presentation"]

[author]
    name = "Jake Howard"
    homepage = "https://theorangeone.net"

[original]
    name = "reveal.js"
    homepage = "https://revealjs.com"
    repo = "https://github.com/hakimel/reveal.js/"
